config/routes.rb
LimayWaterDistrict::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  namespace :admin do
  	match 'login' => "session#new", :via => :get,	:as => "login_page"
  	match 'login' => "session#create", :via => :post,	:as => "login_user"
  	match 'logout' => "session#destroy", :via => :get,	:as => "logout_user"
  	match '/' => 'main#index', :via => :get

		match '/index' => 'main#index', :via => :get
		resources :pages
    resources :posts
    resources :users
    resources :banners
    resources :contacts
    resources :enquiries, only: [:index, :show, :destroy]
    match 'commons/update' => 'main#common_update', :via => :put, :as => 'common_update'
  end
  match '/', to: 'home#index', via: :get
  match '/home', to: 'home#index', :via => :get
  match '/contact-us', to: 'pages#contacts', via: :get, as: 'contact_us'
  match '/enquiry', to: 'pages#send_enquiry', via: :post, as: 'send_enquiry'
  match '/posts', to: 'posts#index', via: :get
  match '/posts/(:page_url)', to: 'posts#show', via: :get, as: 'show_post'
  match '/(:page_url)' => 'pages#show', via: :get, constraints: { page_url: /.*/ }, as: 'pages'
  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  
  def index
    @banners = Banner.where('featured = ? AND activate = ?', true, true)
    @page = Page.where(is_root: true).first
    @archives = Post.active.order('publish_date DESC').group_by {|p| p.publish_date.beginning_of_month rescue p.created_at.beginning_of_month }
    @meta = { title: 'Limay Water District', description: @page.meta_description ? @page.meta_description : '', url: root_url, image:  asset_url('assets/mariwad_office.jpg') }
    #render json: @meta#_description
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :page_styles do %>
    <style>
        <% unless @page.page_styles.nil? || !@page.page_styles.blank? %>
        <%= raw(@page.page_styles) %>
        <% end %>
    </style>
<% end %>
<% content_for :page_content do %>
    <!--home page content starts here -->
<div class="container">
    <div class="col-lg-8">
        <h3 class="page-header well">Lastest News & Info.</h3>
        
        <% @featured_articles.each do |featured| %>
                <div class="row-fluid">
                    <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                        <h3><%= link_to featured.page_title, show_post_path(featured.page_url), class: 'h-news-link' %><br>
                        <small><%= fancy_date(featured.publish_date) %></small>
                        </h3>

                    </div>
                </div>

            <div class="row-fluid">
                <% if featured.photo.present? %>
                  <div class="col-lg-4 col-md-4 col-xs-12 col-sm-12">
                                <a href="<%= featured.photo.url(:large) %>" data-toggle="lightbox" title="<%= featured.page_title %>">
                                        <%= image_tag featured.photo.url(:medium), class: 'img-thumbnail' %>
                                </a>
                </div>
                <div class="col-lg-8 col-md-8 col-xs-12 col-sm-12">
                <% else %>
                <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
                            <% end %>
                                <p class="text-overflow short-desc"><%= raw(short_description(featured.body, 350)) %></p>
                                <%= link_to 'Read More »', show_post_path(featured.page_url), class: 'btn btn-sm btn-primary pull-right' %>
                            </div>
              <div class="clearfix"></div>
              <hr/>
            </div>
            <% end %>
                    <div class="row-fluid bottom-space20">
                        <p class="text-center"><%= link_to 'View All News and Updates', posts_path, class: 'btn btn-sm btn-primary' %></p>
                    </div>


    </div>


    <div class="col-lg-4">
        <br/>
        <br/>        
       <!-- Blog Search Panel -->
            <div class="panel panel-default">
                <div class="panel-heading"><b>Search</b></div>
                <div class="panel-body">
            <%= form_tag posts_path, class: '', method: 'get' do %>
          <div class="input-group">

              <%= text_field_tag :q, params[:q], class: 'form-control' %>
              <span class="input-group-btn">
                  <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
              </span>

          </div>
              <% end %>
                </div>
            </div>

      <!-- Blog Archives Panel -->
           
           <div class="panel panel-default">
                <div class="panel-heading"><b>Archives</b></div>
                <div class="panel-body">
                <% keys = @archives.keys[0..7] %>
                <% if keys.size > 0 %>
                    <% keys.in_groups_of(4).each do |g| %>
                                        <div class="col-lg-6">
                              <ul class="list-unstyled">
                                    <% g.each do |m|  %>
                                        <% if m %>
                                        <li><%= link_to m.strftime('%B %Y'), posts_path(d: m) %></li>
                                          <% end %>
                                      <% end %>
                                                </ul>
                          </div>
                      <% end %>
                  <% end %>
                </div>
            </div>

      <!-- Side Widget Well -->
      <div class="panel panel-default">
          <div class="panel-heading"><b>Popular Links</b></div>
                    <div class="panel-body">
                    <ul class="list-group">

                        <% @popular.each do |page| %>
                            <li class="list-group-item"><%= link_to page.page_title, "/#{page.page_url}", title: page.page_title %></li>
                        <% end %>
                    </ul>
                    </div>

      </div>

            <div class="well">
                <div id="fb-sidebar-widget" class="fb-like-box" data-href="https://www.facebook.com/pages/Mariveles-Water-District/1553420708222422" data-width="100%   " data-height="" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="true" data-show-border="true"></div>
            </div>
</div>
<!--home page content ends here -->

<% end %>

<% content_for :page_scripts do %>
  <script>
	  $(function(){
		  paras = $('.short-desc-news');
		  $.each(paras, function(i,v){
			  $clamp(v, {clamp: 5});
		  })
	  });
  </script>
<% end %>