config/routes.rb
LimayWaterDistrict::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  namespace :admin do
  	match 'login' => "session#new", :via => :get,	:as => "login_page"
  	match 'login' => "session#create", :via => :post,	:as => "login_user"
  	match 'logout' => "session#destroy", :via => :get,	:as => "logout_user"
  	match '/' => 'main#index', :via => :get

		match '/index' => 'main#index', :via => :get
		resources :pages
    resources :posts
    resources :users
    resources :banners
    resources :contacts
    resources :enquiries, only: [:index, :show, :destroy]
    match 'commons/update' => 'main#common_update', :via => :put, :as => 'common_update'
  end
  match '/', to: 'home#index', via: :get
  match '/home', to: 'home#index', :via => :get
  match '/contact-us', to: 'pages#contacts', via: :get, as: 'contact_us'
  match '/enquiry', to: 'pages#send_enquiry', via: :post, as: 'send_enquiry'
  match '/posts', to: 'posts#index', via: :get
  match '/posts/(:page_url)', to: 'posts#show', via: :get, as: 'show_post'
  match '/(:page_url)' => 'pages#show', via: :get, constraints: { page_url: /.*/ }, as: 'pages'
  root :to => 'home#index'

end

app/views/layouts/_footer.html.erb
<div class="content3">
  <div class="container">
      <p>Powered by: <a href="http://inbox.com.ph" style="color:#FFF" target="_blank">Inbox Business Solutions</a> | Limay Water District ©<%= Date.today.year %></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
      <a class="navbar-brand" href="/" style="">
        LIWAD
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <%= raw(build_navs) %>

    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/_main_banners.html.erb
<% if @banners.any? %>
<div id="myCarousel" class="carousel slide">

  <!-- Indicators -->
  <% if @banners.size > 1 %>
  <ol class="carousel-indicators">
    <% @banners.each_with_index do |banner, index|%>
        <li data-target="#myCarousel" data-slide-to="<%= index.to_s %>" <% if banner == @banners.first %>class="active"<% end %>></li>
    <% end %>
  </ol>
  <% end %>
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <% @banners.each_with_index do |item, index|%>
        <div class="item <% if @banners.first == item %>active<% end %>">
          <div class="fill" style="">
            <img src="<%= item.banner.url(:large) %>"/>
          </div>
          <div class="carousel-caption" style="position:absolute;top:30px;">
            <div class="carousel-text">
              <% unless item.title.nil? %><h1 class="animated fadeInDownBig"><%= item.title %></h1><% end %>
              <% unless item.caption.nil? %>
                  <ul class="list-unstyled carousel-list">
                    <li class="animated bounceInLeft" style="padding:10px;"><span style=""><%= item.caption %></span></li>
                  </ul>
              <% end %>
            </div>
          </div>

        </div>
    <% end %>
  </div>

  <!-- Controls -->
  <% if @banners.size > 1 %>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
  <% end %>

</div>
<% end %>

app/views/layouts/_menu_sidebar.html.erb
<nav id="sidebar-menu" class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </li>
            <li id="li-main">
                <a href="<%= admin_path %>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li id="li-pages">
                <a href="<%= admin_pages_path %>"><i class="fa fa-book fa-fw"></i> Pages</a>
            </li>
            <li id="li-news">
                <a href="<%= admin_posts_path %>"><i class="fa fa-bookmark-o"></i> News and Updates</a>
            </li>
            <li id="li-banners">
                <a href="<%= admin_banners_path %>"><i class="fa fa-flag-o"></i> Banners Management</a>
            </li>
						<li id="li-enquiries">
                <a href="<%= admin_enquiries_path %>"><i class="fa fa-phone"></i> Enquiries</a>
            </li>
		        <li id="li-users">
              <a href="<%= admin_users_path %>"><i class="fa fa-users fa-fw"></i> Users</a>
            </li>
            <li id="li-contacts">
                <a href="<%= admin_contact_path(Contact.first) %>"><i class="fa fa-suitcase fa-fw"></i> Company</a>
            </li>
        </ul>
        <!-- /#side-menu -->
    </div>
    <!-- /.sidebar-collapse -->
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= raw(build_navs) %>

    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/administration.html.erb
<!DOCTYPE html>
<html lang="en"><head>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Inbox Biz CMS</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <%= csrf_meta_tags %>
     <!-- Core CSS - Include with every page -->
  	<%= stylesheet_link_tag "css/bootstrap", media: "all" %>
  	<!-- Page-Level Plugin CSS - Dashboard -->
    <%= stylesheet_link_tag "css/plugins/morris/morris-0.4.3.min", media: "all" %>
    <%= stylesheet_link_tag "css/plugins/timeline/timeline", media: "all" %>
    <%= stylesheet_link_tag "css/plugins/dataTables/dataTables.bootstrap", media: "all" %>
    <%= stylesheet_link_tag "css/bootstrap-datepicker", media: "all" %>
    <%= stylesheet_link_tag "css/bootstrap-select/bootstrap-select.min", media: "all" %>
    <%= stylesheet_link_tag "css/jasny-bootstrap.min", media: "all" %>
    <%= stylesheet_link_tag "admin/sb-admin", media: "all" %>
    <meta name="robots" content="noindex">
	  <%= favicon_link_tag 'liwad_icon.png', type: 'image/x-icon' %>

    <%= yield(:page_style) %>
<style>
/*#sidebar-menu li.active{background:#418bca;}*/

</style>
</head>
<body>
    <div id="wrapper">

        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/admin">Inbox Business Solutions CMS</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li style="border-right:1px solid #ccc;"><a href="/" target="_blank"><i class="fa fa-user fa-eye"></i> View Website</a></li>
                <li class="dropdown">

                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    	<%= current_user.username %>
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="<%= admin_logout_user_path %>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

        </nav>
        <!-- /.navbar-static-top -->

		<!-- start sidebar menu here -->
        	<%= render "layouts/menu_sidebar" %>
        <!-- end sidebar menu here -->

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><%= @title %></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- start page content here -->
            <div id="page_content" class="row">
            	<%= yield :page_content %>
            </div>
            <!-- end page content here -->
        </div>
        <!-- /#page-wrapper -->

    </div>





<%= javascript_include_tag "js/jquery-1.11.0.js" %>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "admin/sb-admin.js" %>
<%= javascript_include_tag 'ckeditor/ckeditor.js' %>
<%= javascript_include_tag "js/plugins/metisMenu/jquery.metisMenu.js" %>
<%= javascript_include_tag "js/plugins/morris/raphael-2.1.0.min.js" %>
<%= javascript_include_tag "js/plugins/morris/morris.js" %>
<%= javascript_include_tag "js/plugins/dataTables/jquery.dataTables.js" %>
<%= javascript_include_tag "js/plugins/dataTables/dataTables.bootstrap.js" %>
<%= javascript_include_tag "js/bootstrap-datepicker" %>
<%= javascript_include_tag "js/bootstrap-select/bootstrap-select" %>
<%= javascript_include_tag "js/jasny-bootstrap.min" %>

<%= yield(:page_scripts) %>
<script>
	CKEDITOR.config.allowedContent = true;

  $(function(){
	  $('.selectpicker').selectpicker();
	  $('.fileinput').fileinput();
      <% if flash.any? %>
          <% flash.each do |k,v| %>
            $('#page_content').displayAlert('<%= k %>', '<%= v %>')
          <% end %>
      <% end %>
      current_page = "<%= controller_name %>";
      if($('#li-' + current_page).length > 0){
          $('#li-' + current_page).addClass('active');
      }
	})
</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Limay Water District</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
<%= yield %>

</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Limay Water District</title>
  <%= render 'shared/meta_info' %>
  <%= csrf_meta_tags %>
  <!-- CSS -->
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'css/bootstrap.css' %>
  <%= stylesheet_link_tag 'font-awesome/css/font-awesome.css' %>
  <%= stylesheet_link_tag 'css/front/styles', media: 'all' %>
  <!--page specific styles goes here -->
  <%= yield :page_styles %>
  <!--page specific styles ends here -->

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
  <script src="js/respond.min.js"></script>
  <![endif]-->
  <%= favicon_link_tag 'liwad_icon.png', type: 'image/x-icon' %>
</head>

<body>
<%= render 'shared/fb_init' %>



<%= yield :page_content %>


<!--contents ends here -->


<!-- Scripts -->

<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'main' %>
<%= yield :page_scripts %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55966112-1', 'auto');
  ga('send', 'pageview');

</script>
</body>



</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <title><%= @meta[:title] %></title>
    <%= render 'shared/meta_info' %>
    <%= csrf_meta_tags %>
    <!-- CSS -->
    <%= stylesheet_link_tag 'application', :media => 'all' %>
  <!--page specific styles goes here -->
    <%= yield :page_styles %>
    <!--page specific styles ends here -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
		<![endif]-->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Play' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
	  <%= favicon_link_tag 'liwad_icon.png', :type => 'image/x-icon' %>
</head>

<body>
	<div class="intro-header">
      <div class="container">
	      <%= link_to '/' do %>
			    <%= image_tag 'front/liwad_header.png' %>
				<% end %>
	      <p class="pull-right" style="margin-top:15px; color:#147ec5; font-size:18px">
          <a href="https://www.facebook.com/?q=#/pages/Limay-Water-District/1498438307085675" target="_blank"><span class="fa fa-facebook-square"></span></a>
          <a href=""><span class="fa fa-twitter-square"></span></a>
          <a href=""><span class="fa fa-google-plus-square"></span></a>
          |  <strong><span class="fa fa-phone-square"></span> +63-47-244-5274</strong>
        </p>
      </div>
  </div>
<!--<#%= render 'shared/fb_init' %>-->
<!-- start header here -->
<%= render 'layouts/navigation'  %>
<!-- end header here -->

<% if @banners.any? %>
<!--banners goes here -->
	<%= render 'layouts/main_banners' %>
<!--banners ends here -->
<% end %>
<br />

<div class="content2">
  <div class="container">
		<h1 align="center" style="color:#FFF">Visit our <strong>Transparency Seal</strong>&nbsp;<button class="btn btn-danger btn-lg">View now</button></h1>
  </div>
</div>

<div class="featured_content">
  <div class="container">
    <div class="col-lg-4 col-md-4" align="center">
      <a href="https://www.facebook.com/pages/limaywaterdistrict" target="_blank">
      <div class="panel panel-body">
          <span class="fa fa-facebook-official fa-5x"></span>
          <h3 style="color:#f00">Like us on Facebook</h3>
          <p>For the latest and other related info about your Limay Water District, please visit and like our page</p><br/>
          <button class="btn btn-primary"><span class="fa fa-thumbs-up"></span>&nbsp;Like us on Facebook</button>
      </div>
      </a>
    </div>

    <div class="col-lg-4 col-md-4" align="center">
      <a href="#">
      <div class="panel panel-body">
          <span class="fa fa-cogs fa-5x"></span>
          <h3 style="color:#f00">Citizens Charter</h3>
          <p>To further improve our service to our clients, Limay Water District post its Citizens Charter [...]</p><br/>
          <button class="btn btn-primary"><span class="fa fa-cogs"></span>&nbsp;View now</button>
      </div>
      </a>
    </div>

    <div class="col-lg-4 col-md-4" align="center">
      <a href="#">
      <div class="panel panel-body">
          <span class="fa fa-wrench fa-5x"></span>
          <h3 style="color:#f00">Emergency Leak Report</h3>
          <p>For emergency leak repair and other related concerns, please call, text, email or visit us at [...]</p><br/>
          <button class="btn btn-primary"><span class="fa fa-tint"></span>&nbsp;View now</button>
      </div>
      </a>
    </div>

  </div>
</div>
<div class="clearfix"></div>
<div id="main-section">

  <%= yield :page_content %>
  
</div>

<!-- footer starts here -->
<%= render 'layouts/footer'  %>
<!-- footer ends here -->

<!-- Scripts -->
<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'main' %>

<script type="text/javascript">
    $(document).ready(function ($) {
        var articles = $('#highlights-holder').find('.article');
        // delegate calls to data-toggle="lightbox"
        $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
            event.preventDefault();
            return $(this).ekkoLightbox({
                always_show_close: true
            });
        });

        if(articles.length > 0){
            loopArticles(0);
        };

        function loopArticles(idx){
            if(idx > (articles.length - 1)){
                idx = 0;
            }
            articles.eq(idx)
                    .delay(500)
                    .fadeIn(500, function(){
                        $('#h-loader').fadeOut();
                    })
                    .delay(7000)
                    .fadeOut(700, function(){
                        $('#h-loader').fadeIn(500);
                        loopArticles(idx+1);
                    });

        }
    });
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55966112-1', 'auto');
  ga('send', 'pageview');

</script>
<%= yield :page_scripts %>
</body>



</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <title><%= @meta[:title] %></title>
    <%= render 'shared/meta_info' %>
    <%= csrf_meta_tags %>
    <!-- CSS -->
    <%= stylesheet_link_tag 'application', :media => 'all' %>
  <!--page specific styles goes here -->
    <%= yield :page_styles %>
    <!--page specific styles ends here -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
		<![endif]-->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Play' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
	  <%= favicon_link_tag 'liwad_icon.png', :type => 'image/x-icon' %>
</head>

<body>
	<div class="intro-header">
      <div class="container">
	      <%= link_to '/' do %>
			    <%= image_tag 'front/liwad_header.png' %>
				<% end %>
	      <p class="pull-right" style="margin-top:15px; color:#147ec5; font-size:18px">
          <a href="https://www.facebook.com/?q=#/pages/Limay-Water-District/1498438307085675" target="_blank"><span class="fa fa-facebook-square"></span></a>
          <a href=""><span class="fa fa-twitter-square"></span></a>
          <a href=""><span class="fa fa-google-plus-square"></span></a>
          |  <strong><span class="fa fa-phone-square"></span> +63-47-244-5274</strong>
        </p>
      </div>
  </div>
<!--<#%= render 'shared/fb_init' %>-->
<!-- start header here -->
<%= render 'layouts/navigation'  %>
<!-- end header here -->

<!--contents starts here -->
<% if @banners.any? %>
    <%= render 'layouts/main_banners'  %>
<hr class="page-divider">
<% else %>
<div style="margin-top: 20px;"></div>
<% end %>
<div id="page_content" class="container <%= controller_name %>" style="margin-bottom:20px;">

<%= yield :page_content %>

</div>
<!--contents ends here -->

<!-- footer starts here -->
<%= render 'layouts/footer'  %>
<!-- footer ends here -->

<!-- Scripts -->
<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'main' %>

<script type="text/javascript">
    $(document).ready(function ($) {
        var articles = $('#highlights-holder').find('.article');
        // delegate calls to data-toggle="lightbox"
        $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
            event.preventDefault();
            return $(this).ekkoLightbox({
                always_show_close: true
            });
        });
    });
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55966112-1', 'auto');
  ga('send', 'pageview');

</script>
<%= yield :page_scripts %>
</body>



</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html lang="en"><head>
    
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="">
    <meta name="author" content="">
    <%= csrf_meta_tags %>
	<title>Inbox Business Solutions CMS | Login</title>

    <!-- Core CSS - Include with every page -->
     <!-- Core CSS - Include with every page -->
  	<%= stylesheet_link_tag "css/bootstrap.min.css", media: "all" %>
  	<%= stylesheet_link_tag "font-awesome/css/font-awesome.css", media: "all" %>
  	
	<%= stylesheet_link_tag "admin/sb-admin.css", media: "all" %>
    
	<%= favicon_link_tag 'liwad_icon.png', type: 'image/x-icon' %>
	<style>
		
		.col-centered{
		    float: none;
		    margin: 0 auto ;
		}
		.col-centered img {
			width:120px;
		}
	
	</style>
</head>

<body>

    <div class="container">
    	<%= yield %>
    </div>


<!-- Core Scripts - Include with every page -->
<%= javascript_include_tag "js/jquery-1.11.0.js" %>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "js/bootstrap.min.js" %>
<%= javascript_include_tag "js/plugins/metisMenu/jquery.metisMenu.js" %>


<!-- SB Admin Scripts - Include with every page -->
<%= javascript_include_tag "admin/sb-admin.js" %>
<script>



		
	/* type can be either of the ff
	 alert-success
	 alert-info
	 alert-warning
	 alert-danger
	*/
	$.fn.displayAlert = function(type, msg){
		if(type == ''){
			type = 'alert-warning'; 
		}
		
		aBox = '<div class="alert ' + type + ' alert-dismissable" style="margin-top:15px;">' +
	            '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>' +
	             msg +
	        '</div>';
	    this.prepend(aBox);
	    $('.alert').fadeOut(1000)
	};
	
	
	$.fn.greenify = function() {
	    this.css( "color", "green" );
	};
</script>
</body>

</html>